### ISSUE TITLE
Command-line rummer for the linter

### ISSUE THREAD

**Issue by Potherca** [tomheller/liquid-linter#2]
I was looking for a Liquid linter and this project was the only one I could find.

As it does not have a command line interface, I made the effort to create one: https://github.com/DealerDirect/liquid-linter-cli (Any feedback is welcome).

Would there be any interest in integrating the CLI code into this repository? (And if so, under which circumstances?)

**Comment by tomheller** [comment]
Hey @Potherca. It's awesome that you created a cli wrapper around the linter. I think this can stand as it's own project. I want to keep this repo as simple as possible, as we are using it at my company for a couple of other integrations.

I will link to your CLI repo from the readme.

**Comment by Potherca** [comment]
Thanks for the answer!
