### ISSUE TITLE
{%- -%} syntax throws error

### ISSUE THREAD

**Issue by pavelloz** [tomheller/liquid-linter#3]
I originally posted this issue here: https://github.com/sirlantis/liquid-node/issues/64 but now im not even sure where the problem resides, in the parser or in the interpretation of the liquid that has to be parsed.
Im leaning to the latter, so here I am :)

Correct liquid code (per https://help.shopify.com/themes/liquid/basics/whitespace ):

```
{%- assign test = 'test' -%}
```

Is throwing an error:

```
Tag '{%- assign test = 'test' -%}' was not properly terminated with regexp: undefined
    at {%- assign test = 'test' -%} (undefined:18:1)
```

**Comment by tomheller** [comment]
Hey @pavelloz. Thank you for noticing. The linter more or less brute force liquid parsing, so i think this is more or less an issue with liquid-node. 
I will look into it though and check, just to be sure.

**Comment by pavelloz** [comment]
Thank you :)

**Comment by tomheller** [comment]
```bash
[ { Liquid.SyntaxError: Tag '{%- assign test = 'test' -%}' was not properly terminated with regexp: undefined
      at Document.module.exports.Block.parseToken (./liquid-linter/node_modules/liquid-node/lib/liquid/block.js:88:17)
      at ./liquid-linter/node_modules/liquid-node/lib/liquid/block.js:64:24
      at tryCatcher (./liquid-linter/node_modules/bluebird/js/release/util.js:16:23)
...
    name: 'Liquid.SyntaxError',
    message: 'Tag \'{%- assign test = \'test\' -%}\' was not properly terminated with regexp]
```

Looks like liquid-node does not support whitespace control. Since the linter relies on the parsing mechanism of liquid-node, there's not a lot I can do for you here, sorry.

**Comment by pavelloz** [comment]
Thank you for the investigation :)
